spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      uri: mongodb://localhost:27017/coinCompassAuth
      auto-index-creation: true

##zipking configurations
management:
  tracing:
    sampling:
      probability: 1.0


