#management:
#  tracing:
#    sampling:
#      probability: 0.1

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=api/v1/auth/**

          - id: profile-service
            uri: lb://profile-service
            predicates:
              - Path=api/v1/profile/**

          - id: favorite-service
            uri: lb://favorite-service
            predicates:
              - Path=api/v1/favorite/**


          #Todo: add prediction service for flask/django
