#management:
#  tracing:
#    sampling:
#      probability: 0.1

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"

application:
  security:
    jwt:
      secret-key: 8d4fed75477d160c393db8a22edce23a5ae7971b4533077d89ac0016dd92c879d21791073310294924cb896443a8214cfdc129baa42af8b3030a397382a93532
      expiration: 86400000
      refresh-token:
        expiration: 604800000