spring:
  application:
    name: crypto-service
  config:
    import: "optional:configserver:http://localhost:8088"

##zipking configurations
management:
  tracing:
    sampling:
      probability: 1.0


